# Generated by Django 6.0.2 on 2026-02-28 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Category name', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for URL routing', max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structuring', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Common product name', max_length=255)),
                ('brand', models.CharField(db_index=True, help_text='Brand or manufacturer', max_length=255)),
                ('image_url', models.URLField(blank=True, help_text='URL to the main product image', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed product description')),
                ('slug', models.SlugField(help_text='Unique slug, auto-generated if blank', max_length=500, unique=True)),
                ('category', models.ForeignKey(help_text='Primary category of the product', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(choices=[('Amazon', 'Amazon'), ('Flipkart', 'Flipkart'), ('Myntra', 'Myntra'), ('Croma', 'Croma'), ('RelianceDigital', 'Reliance Digital')], db_index=True, help_text='Name of the retail store', max_length=50)),
                ('store_url', models.URLField(help_text='Direct link to the product on the store', max_length=1000)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Latest retrieved price', max_digits=10)),
                ('availability', models.BooleanField(db_index=True, default=True, help_text='Is the product currently in stock?')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='When the price/availability was last checked')),
                ('product', models.ForeignKey(help_text='Reference to the master product', on_delete=django.db.models.deletion.CASCADE, related_name='store_listings', to='products.product')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('product', 'store_name')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Recorded price at the timestamp', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this price was recorded')),
                ('store_product', models.ForeignKey(help_text='The specific store product listing this price belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.storeproduct')),
            ],
            options={
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
