# Generated by Django 6.0.2 on 2026-02-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product rating on the specific store (e.g., 4.50)', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='store_product',
            field=models.ForeignKey(help_text='The specific store product listing this price belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='products.storeproduct'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='current_price',
            field=models.DecimalField(decimal_places=2, help_text='Latest retrieved price. Decimal for precision.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='product',
            field=models.ForeignKey(help_text='Reference to the master product', on_delete=django.db.models.deletion.CASCADE, related_name='store_variants', to='products.product'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store_name',
            field=models.CharField(choices=[('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart'), ('RELIANCE_DIGITAL', 'Reliance Digital'), ('MYNTRA', 'Myntra'), ('CROMA', 'Croma')], db_index=True, help_text='Name of the retail store', max_length=50),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store_url',
            field=models.URLField(help_text='Direct link to the product page on the store', max_length=1000),
        ),
    ]
