# Generated by Django 6.0.2 on 2026-02-28 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_storeproduct_rating_alter_pricehistory_store_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='Self-referencing mapping for nested hierarchical structuring.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='SKU or GTIN/EAN to precisely match assets across platforms, circumventing text-name discrepancies.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='SEO-friendly unique slug mapping', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Static snap-shot of historic price matrix values.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='store_product',
            field=models.ForeignKey(help_text='Relationship to the exact retailer listing to isolate variations safely.', on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='products.storeproduct'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Accelerated Indexed recording timestamp for blazing Chart.js/Recharts historical API payload serialization.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, help_text='Parent manufacturer label.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Primary domain classification.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Expanded qualitative product information.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secure, globally unique immutable identifier.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Hosted URL to the main product visual representation.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text='Universal product nomenclature.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Auto-generating unique string for frontend routing.', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='availability',
            field=models.BooleanField(db_index=True, default=True, help_text='Boolean logic reflecting instantaneous stock capacities.'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='current_price',
            field=models.DecimalField(decimal_places=2, help_text='Absolute financial metric integer. Guaranteed against floating point precision corruption.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Date metric reflecting chronologic recency from the scraper agent.'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='product',
            field=models.ForeignKey(help_text='Anchor to the master Blueprint entity', on_delete=django.db.models.deletion.CASCADE, related_name='store_variants', to='products.product'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Decentralized store-explicit rating score metric.', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store_name',
            field=models.CharField(choices=[('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart'), ('RELIANCE_DIGITAL', 'Reliance Digital'), ('MYNTRA', 'Myntra'), ('CROMA', 'Croma')], db_index=True, help_text='Verified authorized retailer identity mapping', max_length=50),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store_url',
            field=models.URLField(help_text='Immediate direct URL redirect linkage for consumer acquisition', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'brand'], name='products_pr_name_13ef6e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
    ]
