# Generated by Django 6.0.2 on 2026-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_parent_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft deletion flag. Preserves historical relationships without purging database rows.'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft deletion flag preserving pricing history matrices.'),
        ),
    ]
