# Generated by Django 5.2.11 on 2026-03-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_pricealert_alert_priority_pricehistory_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprice',
            name='is_verified_seller',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeprice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
