# Generated by Django 5.2.11 on 2026-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_storeprice_is_verified_seller_storeprice_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='added_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='last_recorded_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='was_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
